### ISSUE TITLE
Docker-image won't start // Database connection error

### ISSUE THREAD

**Issue by leisefuxX** [pawelmalak/snippet-box#46]
when i follow the instructions on github page and want to start snippet-box i get the following:

`[2022-03-01 07:43:40.153 UTC+0] [INFO] db: Database connected
[2022-03-01 07:43:40.178 UTC+0] [INFO] db: Found pending migrations. Executing...
[2022-03-01 07:43:40.197 UTC+0] [ERROR] db: Database connection error`

i deployed the container with docker (`docker run ...`) and docker-compose and the .yml from the repository. i sticked to the given example. error is always the same. the logs get spammed with the 3 lines given. 

i am running docker on ubuntu 20.04.3 x64, latest updates and upgrades, docker from official repo. can provide any logs and outputs. just ask (:

**Comment by Binaryzero** [comment]
check this issue, it worked for me
https://github.com/pawelmalak/snippet-box/issues/19

**Comment by natget21** [comment]
I am facing the same issue as well I run it on raspberry pi using the arm tag

**Comment by chrisbward** [comment]
+1

**Comment by chrisbward** [comment]
https://github.com/pawelmalak/snippet-box/issues/34

Spotted this issue - could be because I'm using named volumes

**Comment by null-affinity** [comment]
I'm getting this condition as well. Also using named volumes.

**Comment by Trevo525** [comment]
I can also confirm. I kept getting an error with the following `docker-compose.yml`:
```
version: '3.3'
services:
    snippet-box:
        image: pawelmalak/snippet-box
        container_name: snippet-box
        restart: unless-stopped
        ports:
            - '5000:5000'
        volumes:
            - 'snippet-box-data:/app/data'
        networks:
            - reverse-proxy-network

volumes:
    snippet-box-data:
            external: true

networks:
    reverse-proxy-network:
        external: true
```
I changed the Volume to a Bind Mount in the following `docker-compose.yml` file and it has been working fine for me.
```
version: '3.3'
services:
    snippet-box:
        image: pawelmalak/snippet-box
        container_name: snippet-box
        restart: unless-stopped
        ports:
            - '5000:5000'
        volumes:
            - './data:/app/data'
        networks:
            - reverse-proxy-network

networks:
    reverse-proxy-network:
        external: true
```
